# Generated by Django 2.2.10 on 2020-04-15 06:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insights',
            new_name='Insight',
        ),
    ]
