# Generated by Django 2.2.10 on 2020-06-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0003_insightindexpage_insightpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='insightpage',
            name='tags',
            field=models.ManyToManyField(blank=True, to='home.Tag'),
        ),
    ]
