# Generated by Django 2.2.10 on 2020-06-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0004_auto_20200627_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insightpage',
            name='tags',
            field=models.ManyToManyField(to='home.Tag'),
        ),
    ]
